apiVersion: v2
name: auth-service-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.3
appVersion: 1.0.5

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 6.14.8
    condition: mysql.enabled
    tags:
      - myapp-database

