apiVersion: v2
name: user-service-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: 1.1.3

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 6.14.8
    condition: mysql.enabled
    tags:
      - myapp-database

