replicaCount: 2

image:
  repository: bpastukh/user-service

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  annotations: {nginx.ingress.kubernetes.io/rewrite-target: /$2}
  hosts:
    - host: arch.homework
      paths: ["/otusapp/bgpastukh/user-service($|/)(.*)"]
  tls: []

mysql:
  enabled: true
  db:
    user: user
    password: pass
    name: user-service
  service:
    port: "3306"
    type: NodePort

authService:
  baseUrl: "http://auth-service-auth-service-chart"
  namespace: "default"
  port: "8000"